#!/bin/bash

# colors
green="\e[1;32m";
red="\e[1;91m";
reset="\e[0m";

if [ -f ~/.ignore_dots ]; then
	a=$(find . -type f ! -path './.git/*' ! -path './.icons/*' | grep -vFf ~/.ignore_dots);
else
	a=$(find . -type f ! -path './.git/*' ! -path './.icons/*');
fi

for remote_file in ${a}; do
	home_path=$(echo $HOME | sed 's/\//\\\//g')
	local_file=$(echo $remote_file | sed "s/^\./$home_path/");
	home_file=$(echo $remote_file | sed "s/^\./~/");
	if [ -f $local_file ]; then
		local_hash=$(md5sum $local_file | sed "s/\ .*//g");
		remote_hash=$(md5sum $remote_file | sed "s/\ .*//g");
		if [[ $local_hash != $remote_hash ]]; then
			vimdiff $remote_file $local_file;
			echo -e "${green}UPDATED${reset} ${home_file}";
		fi
	else
		echo -e "${red}NO FILE${reset} ${home_file}";
	fi
done
