#!/bin/bash

spotify-controller &> /dev/null

[ $? -eq 1 ] && exit

if spotify-controller status | grep 'Paused' > /dev/null; then
	printf '\xef\x81\x8c ' # fa-pause
else
	printf '\xef\x81\x8b ' # fa-play
fi

# print artist | music
output=$(spotify-controller current-oneline)

# if output too long
if [[ $(echo -n $output | wc -c) -gt 35 ]]; then
	# print music
	output=$(spotify-controller current | awk 'END{$1=""; print substr($0, 2)}')
fi

# if output too long
if [[ $(echo -n $output | wc -c) -gt 35 ]]; then
	# print artist
	output=$(spotify-controller current | awk 'FNR==2{$1=""; print substr($0, 2)}')
fi

echo -n $output
